version: '3.1'

services:
  db:
    image: mysql:8.0.23
    container_name: system-order-service-database
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estagio_hiragi