spring:
    datasource:
        password: root
        username: root
        url: jdbc:mysql://db:3306/estagio_hiragi
    jpa:
        hibernate:
            ddl-auto: validate

logging.level.org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE